#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/reels-platform"
unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
env_file="$config_dir/systemd.env"

mkdir -p "$config_dir" "$unit_dir"
(
  umask 077
  cat > "$env_file" <<ENV
# Generated by scripts/install-systemd.sh. This file contains paths only.
REELS_PROJECT_DIR=$project_dir
REELS_DB_PATH=$project_dir/db/reels.db
ENV
)

install -m 644 "$project_dir"/deploy/systemd/reels-web.service "$unit_dir"/
install -m 644 "$project_dir"/deploy/systemd/reels-weekly.service "$unit_dir"/
install -m 644 "$project_dir"/deploy/systemd/reels-weekly.timer "$unit_dir"/
systemctl --user daemon-reload
systemctl --user enable --now reels-web.service reels-weekly.timer
printf 'Installed Reels Platform services for %s\n' "$project_dir"
